- src/routes/chat/+page.svelte
- src/routes/dashboard/+page.server.ts
- src/routes/join/+page.server.ts
- src/routes/join/+page.svelte
recent sessions:
- return the created and joined sessions from backend
grouping:
- add join column in the join page
- add document 'groups' in firestore
- add group information in  the session
chat page:
- add a sample chat page
> feat: add recent sessions(backend), grouping and chat page

- src/lib/types/IndividualDiscussion.ts
- src/lib/types/groupDiscussion.ts
- src/lib/types/resource.ts
- src/lib/types/session.ts
- src/lib/types/speech.ts
Add Firestore data structures for type definition.
> Add Firestore data structures

- src/lib/components/Sidebar.svelte
- src/lib/firebase/store.ts
- src/lib/schema/code.ts
- src/lib/schema/conversation.ts
- src/lib/schema/group.ts
- src/lib/schema/profile.ts
- src/lib/schema/resource.ts
- src/lib/schema/session.ts
- src/lib/schema/template.ts
- src/routes/api/session/+server.ts
- src/routes/api/session/[id]/stage/+server.ts
- src/routes/api/template/+server.ts
- src/routes/api/template/[id]/+server.ts
- src/routes/api/template/[id]/resource/+server.ts
- src/routes/api/template/[id]/resource/[resourceId]/+server.ts
- src/routes/create/+page.server.ts
- src/routes/dashboard/+page.svelte
- src/routes/join/+page.svelte
- src/routes/session/[id]/+layout.svelte
- src/routes/session/[id]/+page.svelte
This pull request introduces several significant changes, primarily focusing on schema updates, API enhancements, and UI improvements. The most important changes include updates to various schemas, additions of new API endpoints, and modifications to the `Sidebar` and `Dashboard` components.
Schema Updates:
* [`src/lib/schema/conversation.ts`](diffhunk://#diff-97c8aeacc456a8d06a4b73b35c6c457dbdd1bea24c490d0606587a1051c32760R2-R16): Added new fields such as `task`, `subtasks`, `resources`, and `audio` to the `ConversationSchema`.
* [`src/lib/schema/group.ts`](diffhunk://#diff-700cd95abc85a8aa5d6c9352ca3ad5da23a070887324f23219c9b89f686c4e23R3-R16): Introduced new fields `participants`, `speaker`, and updated `keywords` constraints in the `GroupSchema`.
* …
> feat: refine schema

- package.json
- src/injection/env/private.ts
- tsconfig.tsx.json
This pull request includes several changes to the project configuration and environment setup. The most important changes involve updating scripts in `package.json`, adding environment variable support, and creating a new TypeScript configuration file.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L15-R17): Updated the `stt` and `pdf` scripts to use `pnpm` and added a new `tsx` script.
* [`src/injection/env/private.ts`](diffhunk://#diff-0ba86838b44c7f5f35ed782bc9b9b3acdfcab584e5af68cb01bdd591d752d71eR1-R5): Added dotenv configuration to load environment variables from a `.env` file.
* [`tsconfig.tsx.json`](diffhunk://#diff-3c8298808eaab9c7337fccbe71c0f3dae780b7053ef31c952b6627618eff7700R1-R17): Created a new TypeScript configuration …
> chore: tsconfig for direct execution

- src/lib/schema/profile.ts
resolve #24 
This pull request includes changes to the `src/lib/schema/profile.ts` file to enhance validation for the `ProfileSchema` object. The most important change is the addition of length constraints for the `displayName`, `title`, and `bio` fields.
Enhancements to validation:
* [`src/lib/schema/profile.ts`](diffhunk://#diff-2a8b4aa90b544f3c299888d97ee89916375b4165a6a81dd28a9a2d2ac2e13c78L8-R10): Added `.min(1).max(100)` constraints to the `displayName` and `title` fields, and `.min(1).max(1000)` constraint to the `bio` field to ensure valid input lengths.
> fix: unlimited display name

- package.json
- pnpm-lock.yaml
- src/lib/components/AudioPlayer.svelte
- src/lib/components/Chatroom.svelte
- src/lib/components/session/HostView.svelte
- src/routes/test/chatroom/+page.svelte
New Chatroom component, should work with multiple scenarios and support readonly mode. 
Dependency Management:
* Removed `pdf-parse` and `parse` dependencies from `package.json` and `pnpm-lock.yaml`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L71-R71) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL9-L18) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL6607-L6613)
* Updated `llamaindex` to version `0.8.30` in `package.json` and `pnpm-lock.yaml`. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R44-L52) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL5801-R5752)
> feat: chatroom component

- package.json
- pnpm-lock.yaml
- src/lib/components/Chatroom.svelte
- src/routes/api/stt/+server.ts
- src/routes/test/chatroom/+page.svelte
- vite.config.ts
This pull request includes several updates to dependencies and enhancements to the `Chatroom.svelte` component to support audio recording and transcription. The most important changes include adding new dependencies, updating the `Chatroom.svelte` component to handle audio recording, and configuring the Vite plugin for static file copying.
* Added `@ricky0123/vad-web` and `onnxruntime-web` to `package.json` and updated `pnpm-lock.yaml` to include these new dependencies. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R21) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R48) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR13-R15) …
> feat: vad prototype

- src/routes/template/[id]/+page.svelte
- src/routes/template/[id]/ResourceList.svelte
This pull request includes several changes to the `src/routes/template/[id]/+page.svelte` file and the `src/routes/template/[id]/ResourceList.svelte` file. The main focus is on improving the user experience by integrating a notification system and managing the state of the upload process.
* `src/routes/template/[id]/+page.svelte`: Removed the `Alert` component and replaced inline error and success messages with the `notifications` store for better user feedback. ([src/routes/template/[id]/+page.svelteL2-R2](diffhunk://#diff-e307aca68c54d08af897f33b2c097e57a9c2548828f5d333d6a86b2f9b45c189L2-R2), [src/routes/template/[id]/+page.svelteL58-R62](diffhunk://#diff-e307aca68c54d08af897f33b2c097e57a9c2548828f5d333d6a86b2f9b45c189L58-R62), …
> fix: uploading file and display issue

- package.json
- scripts/createTestStudent.ts
- src/lib/schema/group.ts
modify group time schema to TimeStamp(align with schema of profile)
> fix Teststudent, modify group schema 

- src/routes/dashboard/+page.svelte
> fix: sec rule update

- src/lib/components/Auth.svelte
- src/lib/components/Navbar.svelte
- src/lib/components/ResolveUsername.svelte
- src/lib/components/SessionCard.svelte
- src/lib/components/TemplateCard.svelte
- src/lib/components/session/HostView.svelte
- src/lib/components/session/LabelManager.svelte
- src/lib/utils/getUser.ts
- src/routes/dashboard/+page.svelte
- src/routes/dashboard/recent/host/+page.svelte
- src/routes/dashboard/recent/participant/+page.svelte
- src/routes/profile/+page.server.ts
- src/routes/profile/+page.svelte
- src/routes/template/[id]/+page.svelte
- src/routes/templates/public/+page.svelte
This pull request includes several updates to various components, focusing on enhancing the user interface, adding new functionalities, and improving code maintainability. The most important changes include the integration of new components, the addition of tooltips for better user guidance, and the refactoring of existing components for better code organization.
* [`src/lib/components/Auth.svelte`](diffhunk://#diff-eafa1c1bc4d2d2b3705d5871ac38a9b6811f17960030c90b3b6f90099def77f7L2-R10): Replaced the "Sign Out" button with a "Dashboard" button using the `Button` component from `flowbite-svelte`.
* [`src/lib/components/Navbar.svelte`](diffhunk://#diff-1d2ad6a3da75a887eb8578849e9baec3e174d19671b9b281a5d2413995235fc1L2-R7): Added the `Button` component from `flowbite-svelte` and updated the …
> UI improvements

- .github/workflows/build-and-push.yml
- Dockerfile
- docker-compose.yml
- package.json
- pnpm-lock.yaml
- svelte.config.js
This pull request introduces several significant changes, primarily focusing on Docker integration, dependency updates, and configuration adjustments for the SvelteKit project. The most important changes include the addition of a GitHub Actions workflow for building and pushing Docker images, the creation of a `Dockerfile` and `docker-compose.yml` for containerization, and updates to dependencies and configurations in `package.json`, `pnpm-lock.yaml`, and `svelte.config.js`.
* Added GitHub Actions workflow to build and push Docker images (`.github/workflows/build-and-push.yml`).
* Created `Dockerfile` for building the application in a Docker container.
* Added `docker-compose.yml` for defining and running multi-container Docker applications.
* Updated `package.json` to include new …
> Dockerize and CI

- src/hooks.server.ts
- src/lib/components/Auth.svelte
- src/lib/stores/auth.ts
This pull request includes several changes to improve the authentication flow and user interface in the application. The most important changes include adding a new route exception for sign out, enhancing the user interface for authenticated users, and adding logging for authentication state changes.
Enhancements to authentication flow:
* [`src/hooks.server.ts`](diffhunk://#diff-b5aa13ce0a61c3f166000471d0729aa6a8e57292fdbd8d88452443502e4b9a4aR28): Added a new route exception for `/api/auth/signout` to the authentication middleware to allow users to sign out without being authenticated.
* [`src/lib/stores/auth.ts`](diffhunk://#diff-11eb8337e0ac09aafd9bd61b6a1b86ce1b586fa6a11752390d55a15da4d78abfR49-R51): Updated the `signOut` function to check if there is a current user before attempting …
> fix: auth bug

- src/hooks.server.ts
- src/lib/components/Auth.svelte
- src/lib/stores/auth.ts
- src/routes/join/+page.svelte
- src/routes/login/+page.server.ts
- src/routes/session/[id]/+page.server.ts
Students can scan the QR code and, upon logging in, be seamlessly redirected to their previous session without any further actions required.
> feat: redirect to previous session after login

- .gitignore
- src/lib/components/Auth.svelte
- src/lib/components/Chatroom.svelte
- src/lib/stores/auth.ts
This PR addresses two important issues:
- **Fixes authentication redirection after login**
- **Optimizes the chatroom scroll behavior to improve user experience**
---
Previously, when a user signed in with Google and had a session URL parameter, the redirection wasn't working properly due to issues with the URL sanitization process. This PR implements a more robust approach:
- Added proper handling of session URLs in the authentication flow using the **URL API** for robust parsing  
- Implemented error handling for URL parsing with appropriate fallbacks  
- Improved redirection mechanism to maintain **query parameters** and **path components**  
- Fixed the button text to dynamically show `"GoToNextPage"` when a session parameter is present
---
The chatroom previously scrolled …
> Pull Request: Fix Auth Redirect and Optimize Chatroom Scroll

- messages/en.json
- messages/zh.json
- src/lib/components/session/HostView.svelte
- src/lib/components/session/ParticipantView.svelte
- src/routes/api/session/[id]/group/auto_group/+server.ts
This pull request includes several changes to enhance the group management functionality and improve the user experience in the session management components. The most important changes include updates to the language files, modifications to the `HostView.svelte` component to handle group applications more effectively, and adjustments to the `ParticipantView.svelte` component to support waitlist management.
* [`messages/en.json`](diffhunk://#diff-5d9e5048516ec2fe83ca06813e79c3b8b44c6c96294f25c7311db311e28eeaeeL200-R206): Added new messages related to group management and participant notifications.
* [`messages/zh.json`](diffhunk://#diff-b1da422c0458d9d7093c9418675ac11a7d276d2d366636a493cca8e90dd75912R183-R189): Added translations for new messages related to group management and …
> feat: group status

- src/lib/server/gemini.ts
- src/lib/server/prompt.ts
- src/lib/server/types.ts
- src/lib/stt/gemini.ts
- src/routes/api/session/[id]/group/[group_number]/conversations/[conv_id]/summary/+server.ts
- src/routes/api/session/[id]/group/[group_number]/discussions/add/+server.ts
This pull request introduces several changes to the `src/lib/server/gemini.ts` file and related files, focusing on adding a new feature to provide help messages and updating existing prompts. The most important changes include the addition of the `getHeyHelpMessage` function, modifications to prompt constants, and updates to the handling of subtasks and discussions.
* [`src/lib/server/gemini.ts`](diffhunk://#diff-c2a6f86757120491865be9bb731662dcbcc014587ed8f79e2bdd099906a86d7bR315-R358): Added `getHeyHelpMessage` function to generate help messages based on the current task, subtasks, and resources.
* `src/routes/api/session/[id]/group/[group_number]/discussions/add/+server.ts`: Integrated `getHeyHelpMessage` to respond to specific help requests in discussions. …
> feat: support "hey" keyword spotting function in discussion stage

- src/lib/server/gemini.ts
This pull request refactors the variable naming in `src/lib/server/gemini.ts` to follow the project's camelCase naming convention, improving code consistency and readability across the codebase. It also removes an unnecessary use of the normalizeText function in the cleanForeignLanguage function.
- Renamed all snake_case variables to camelCase format throughout the file
- Examples include:
- `system_prompt` → `systemPrompt`
- `parsed_result` → `parsedResult`
- `formatted_docs` → `formattedDocs`
- `normalized_response` → `normalizedResponse`
- `similar_view_points` → `similarViewPoints`
- `student_opinion` → `studentOpinion`
- Removed unnecessary normalizeText function call in cleanForeignLanguage for better performance
These changes adhere to the project naming convention rule which …
> # PR: Refactor variable naming in gemini.ts to follow camelCase convention

- src/lib/server/prompt.ts
- src/routes/api/session/[id]/group/[group_number]/discussions/add/+server.ts
internal tracker: N-004
This pull request simplifies and optimizes the content processing pipeline in our application by removing unnecessary foreign language detection and cleaning steps. This change reduces complexity, improves performance, and simplifies the codebase.
- Removed the `cleanForeignLanguage` function and all related logic from the discussion content processing flow
- Updated content variables throughout the codebase to directly use original content for harmful content checks
- Simplified response structures by eliminating unnecessary properties in success responses
- Removed redundant language processing logic in various utility functions
The foreign language detection and cleaning process was adding unnecessary complexity and processing overhead to our application. After …
> PR: Streamline discussion content processing by removing foreign language checks

- src/lib/schema/utils.ts
should fix N-001 settings not applied bug.
> fix: improve Timestamp validation logic

- messages/en.json
- messages/zh.json
- src/lib/components/template/LabelManager.svelte
- src/routes/template/[id]/+page.svelte
This pull request introduces several changes to enhance user feedback messaging and improve the robustness of event handling in the template management feature. The most important changes include adding new localized strings for user notifications, refactoring notification messages to use these localized strings, and improving event handling in the `LabelManager` component.
* Added new localized strings for user notifications in `messages/en.json` and `messages/zh.json`, including messages for saving templates, removing subtasks, creating sessions, and deleting templates. [[1]](diffhunk://#diff-5d9e5048516ec2fe83ca06813e79c3b8b44c6c96294f25c7311db311e28eeaeeL323-R328) [[2]](diffhunk://#diff-b1da422c0458d9d7093c9418675ac11a7d276d2d366636a493cca8e90dd75912L324-R329)
* Updated notification …
> Fix template double update

- src/routes/template/[id]/+page.svelte
This pull request updates the `+page.svelte` file to enhance the class selection functionality by including additional metadata for classes and displaying it in the dropdown menu. The most significant changes involve expanding the `classes` object structure and updating how class information is rendered.
Enhancements to class metadata:
* `src/routes/template/[id]/+page.svelte`: Expanded the `classes` array to include `schoolName` and `academicYear` properties, in addition to `id` and `className`. ([src/routes/template/[id]/+page.svelteL31-R31](diffhunk://#diff-e307aca68c54d08af897f33b2c097e57a9c2548828f5d333d6a86b2f9b45c189L31-R31))
* `src/routes/template/[id]/+page.svelte`: Updated the `classes` mapping logic to populate the new `schoolName` and `academicYear` fields from the …
> feat: enhance class display in template page
