hinagiku-dev/Hinagiku

- vite.config.ts
This pull request involves a significant change to the `vite.config.ts` file, specifically the removal of the `vite-plugin-static-copy` plugin and its associated configurations.
* [`vite.config.ts`](diffhunk://#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddL3-R5): Removed the `viteStaticCopy` plugin and its configuration for copying various files from `node_modules` to the destination directory. The `plugins` array now only includes `sveltekit()`.
> build: no bundle wasm

- src/routes/api/auth/signin/+server.ts
- src/routes/profile/+page.server.ts
This pull request includes several changes to the authentication and profile management functionality. The main updates involve importing additional modules, verifying user tokens, creating default profiles, and validating profile data using a schema.
* [`src/routes/api/auth/signin/+server.ts`](diffhunk://#diff-23e4ffc55887d0dd630e0ec5a066bf7e8dc94c94998d33e539727dd41c0c996bL1-R3): Added imports for `adminDb` and `FieldValue` from `firebase-admin/firestore`. Implemented logic to verify user tokens and create default profiles if they do not exist. Updated error message for sign-in failures. [[1]](diffhunk://#diff-23e4ffc55887d0dd630e0ec5a066bf7e8dc94c94998d33e539727dd41c0c996bL1-R3) [[2]](diffhunk://#diff-23e4ffc55887d0dd630e0ec5a066bf7e8dc94c94998d33e539727dd41c0c996bR23-R45)
* …
> feat: create profile on signup and signin

- src/lib/components/session/EndedView.svelte
- src/lib/components/session/HostView.svelte
- src/lib/components/session/ParticipantView.svelte
- src/lib/server/llm.ts
- src/lib/utils/firestore.ts
- src/routes/+page.svelte
- src/routes/api/session/[id]/group/[group_number]/conversations/[conv_id]/chat/+server.ts
- src/routes/api/session/[id]/group/[group_number]/conversations/[conv_id]/remove/warning/+server.ts
- src/routes/dashboard/+page.svelte
- src/routes/dashboard/recent/host/+page.svelte
- src/routes/dashboard/recent/participant/+page.svelte
- src/routes/session/[id]/+page.svelte
This pull request includes several changes to improve the functionality and user experience of the application. The most important changes include updating button styles, adding a new function for handling warnings, and ensuring proper handling of conversation warnings. Additionally, several pages now have dynamic titles for better user navigation.
UI Improvements:
* [`src/lib/components/session/EndedView.svelte`](diffhunk://#diff-46b4737e818d95d9042067797c481e6ba3ce01ee07df7402c841c23a93a354efL50-R74): Updated button styles to use `bg-primary-600` instead of `bg-blue-500` for better consistency with the design system.
New Functionality:
* [`src/lib/components/session/HostView.svelte`](diffhunk://#diff-0c3dc447ca6aa7d6aa43b5d504989e13fc71f341d2db088bd3c9e6924034bf1fR267-R299): Added …
> feat: warning handling, page title and button style in EndedView 

- src/lib/components/session/HostView.svelte
- src/lib/components/session/MostActiveParticipants.svelte
- src/lib/utils/firestore.ts
- src/routes/api/session/[id]/conversations/+server.ts
- src/routes/api/session/[id]/conversations/keywords/+server.ts
- src/routes/api/session/[id]/conversations/most-active-participants/+server.ts
This pull request includes several changes to enhance the functionality and data handling in the `HostView` component and related modules. The most important changes include adding new data fetching functions, updating components to handle new data, and adding new API endpoints.
Data fetching and state management:
* [`src/lib/components/session/HostView.svelte`](diffhunk://#diff-0c3dc447ca6aa7d6aa43b5d504989e13fc71f341d2db088bd3c9e6924034bf1fR77-R78): Introduced `conversationsData` and `keywordData` states, and added `loadConversationsData` and `loadKeywordData` functions to fetch data from new API endpoints. These functions are called when the session status is 'ended'. [[1]](diffhunk://#diff-0c3dc447ca6aa7d6aa43b5d504989e13fc71f341d2db088bd3c9e6924034bf1fR77-R78) …
> feat: show most active participants and groups, word cloud in Ended Stage

- src/routes/api/session/[id]/conversations/keywords/+server.ts
This pull request includes a change to the `GET` request handler in the `src/routes/api/session/[id]/conversations/keywords/+server.ts` file. The change improves the calculation of keyword frequencies by correctly using the keyword as the key and adding the count to the existing frequency.
* `src/routes/api/session/[id]/conversations/keywords/+server.ts`: Modified the `Object.entries` method to correctly use `keyword` as the key and add `count` to `keywordFrequency`. ([src/routes/api/session/[id]/conversations/keywords/+server.tsL16-R17](diffhunk://#diff-ab41db5e4999fe1f7249de066d1c88b1d98329168f66e6e8819ef00e3468713dL16-R17))
> fix: keyword is not fetched correctly in API

- src/lib/components/QrScanner.svelte
- tests/firebase.test.ts
- tests/getUser.test.ts
This pull request includes changes to enhance error handling in the `QrScanner` component and adds extensive unit tests for Firebase-related functions. The most important changes include improved error messaging for QR code scanning, and the addition of unit tests for Firebase server functions and user data retrieval.
Error handling improvements:
* [`src/lib/components/QrScanner.svelte`](diffhunk://#diff-fd74a6040d19e4f4a209076e95cfdf92374226f28377f2539e3989215d22127cL39-R46): Enhanced error messaging for QR code scanning by checking for `NotFoundException` and providing more specific error messages. [[1]](diffhunk://#diff-fd74a6040d19e4f4a209076e95cfdf92374226f28377f2539e3989215d22127cL39-R46) [[2]](diffhunk://#diff-fd74a6040d19e4f4a209076e95cfdf92374226f28377f2539e3989215d22127cL56-R67) …
> fix: qr code show not found exception handling

- src/lib/components/session/StageProgress.svelte
This pull request includes a change to the `StageProgress.svelte` file to improve the user experience during stage transitions. The most important change is the addition of a condition to handle the loading state for the "Previous" button, ensuring that it is disabled appropriately during the loading process.
User experience improvement:
* [`src/lib/components/session/StageProgress.svelte`](diffhunk://#diff-2f9d93aa3b5adaaf7b2bbbc60e2c4f5833aea1c8c5d76adac61abe94a780f9c9L94-R94): Added `loadingPrevious` condition to the "Previous" button to handle the loading state and ensure it is disabled when necessary.
> fix: previous stage not show on loading

- src/lib/components/session/EndedView.svelte
- src/lib/components/session/HostView.svelte
- src/lib/components/session/ParticipantView.svelte
This pull request includes changes to the naming convention for the AI assistant in multiple components. The AI assistant's name has been updated from 'AI Assistant' to '小菊(Hinagiku)'.
Updates to naming convention:
* [`src/lib/components/session/EndedView.svelte`](diffhunk://#diff-46b4737e818d95d9042067797c481e6ba3ce01ee07df7402c841c23a93a354efL20-R20): Changed the AI assistant's name to '小菊(Hinagiku)' in the conversation history mapping.
* [`src/lib/components/session/HostView.svelte`](diffhunk://#diff-0c3dc447ca6aa7d6aa43b5d504989e13fc71f341d2db088bd3c9e6924034bf1fL379-R379): Updated the AI assistant's name to '小菊(Hinagiku)' in the selected participant's conversation history.
* [`src/lib/components/session/ParticipantView.svelte`](diffhunk://#diff-476a3db584a448488a3a1ac20e53027b048ac557 …
> sytle: change ai assistant name

- src/lib/components/session/GroupSummary.svelte
- src/lib/components/session/ParticipantView.svelte
- src/lib/server/types.ts
- src/routes/api/session/[id]/group/[group_number]/discussions/summary/+server.ts
This pull request includes several changes to the `GroupSummary.svelte`, `ParticipantView.svelte`, `types.ts`, and `+server.ts` files. The main improvements focus on updating the handling of keywords, adding new UI elements, and modifying data structures.
* [`src/lib/components/session/GroupSummary.svelte`](diffhunk://#diff-dc8a44a089a402d73b71ebbfdf6381efab1453ca5ad71277e0342a2c4feade30R4-R49): Changed the `onUpdate` function to accept a `Record<string, number>` for keywords instead of an array of strings. Updated the `editedKeywords` structure to include text and weight properties, and modified the keyword sorting and mapping logic accordingly.
* [`src/lib/components/session/GroupSummary.svelte`](diffhunk://#diff-dc8a44a089a402d73b71ebbfdf6381efab1453ca5ad71277e0342a2c4feade30L87-R120): …
> fix: summary not shown properly, change keywords style

- src/lib/components/session/ParticipantView.svelte
- src/lib/stt/gemini.ts
work around on resolving #78 
This pull request includes several changes to improve audio processing and transcription functionalities. The key changes involve trimming audio data and cleaning up transcription results.
Audio processing improvements:
* [`src/lib/components/session/ParticipantView.svelte`](diffhunk://#diff-476a3db584a448488a3a1ac20e53027b048ac557d6928a0041b5af3b33901f96L218-R219): Modified the `float32ArrayToWav` function call to remove the last 8000 samples (0.5 seconds) from the audio data before converting it to WAV format. This change was made in two places within the file. [[1]](diffhunk://#diff-476a3db584a448488a3a1ac20e53027b048ac557d6928a0041b5af3b33901f96L218-R219) [[2]](diffhunk://#diff-476a3db584a448488a3a1ac20e53027b048ac557d6928a0041b5af3b33901f96L379-R381) …
> fix: ASR hallucination on ending silence

- src/lib/components/Chatroom.svelte
- src/lib/components/session/HostView.svelte
- src/lib/components/session/ParticipantView.svelte
- src/lib/server/firebase.ts
- src/routes/api/auth/signin/+server.ts
This pull request includes several changes to improve the layout and functionality of the chatroom and session components, as well as updates to the server-side logic for creating conversations and user sign-in. The most important changes include modifications to the `Chatroom.svelte`, `HostView.svelte`, and `ParticipantView.svelte` components, as well as updates to the Firebase server and sign-in API.
Improvements to chatroom layout:
* [`src/lib/components/Chatroom.svelte`](diffhunk://#diff-31a2070f41fdaa274729f68d27df9e502cdb6c29abe9e0525b095d68de81cacdL82-R82): Added minimum height to the chat container and adjusted the layout of the message input area to improve responsiveness and usability. [[1]](diffhunk://#diff-31a2070f41fdaa274729f68d27df9e502cdb6c29abe9e0525b095d68de81cacdL82-R82) …
> fix&style: conversation can't create when join existing group after started, improve layout

- src/lib/components/Chatroom.svelte
This pull request includes changes to the `Chatroom.svelte` file to improve the user experience by adding a message for when there are no conversations.
User experience improvements:
* [`src/lib/components/Chatroom.svelte`](diffhunk://#diff-31a2070f41fdaa274729f68d27df9e502cdb6c29abe9e0525b095d68de81cacdR84-R88): Added a conditional check to display a message prompting the user to reload the page when there are no conversations. [[1]](diffhunk://#diff-31a2070f41fdaa274729f68d27df9e502cdb6c29abe9e0525b095d68de81cacdR84-R88) [[2]](diffhunk://#diff-31a2070f41fdaa274729f68d27df9e502cdb6c29abe9e0525b095d68de81cacdR120)
> style: show reload message if no conversations

- src/lib/components/session/HostView.svelte
- src/routes/dashboard/+page.svelte
- src/routes/dashboard/recent/host/+page.svelte
- src/routes/dashboard/recent/participant/+page.svelte
- src/routes/template/[id]/+page.svelte
This pull request includes several changes aimed at improving the user interface and user experience across multiple components and pages. The primary focus is on enhancing the layout and readability of session and template titles, as well as improving the visual representation of session statuses.
Improvements to session and template title layout:
* [`src/lib/components/session/HostView.svelte`](diffhunk://#diff-0c3dc447ca6aa7d6aa43b5d504989e13fc71f341d2db088bd3c9e6924034bf1fL486-R486): Refactored the layout to use a more flexible column-based structure for better alignment and spacing of session titles and labels. [[1]](diffhunk://#diff-0c3dc447ca6aa7d6aa43b5d504989e13fc71f341d2db088bd3c9e6924034bf1fL486-R486) [[2]](diffhunk://#diff-0c3dc447ca6aa7d6aa43b5d504989e13fc71f341d2db088bd3c9e69 …
> fix: bug template with title in english characters without spaces will cause UI issue, minor style updated

- src/lib/components/Chatroom.svelte
- src/lib/components/session/ParticipantView.svelte
This pull request includes several enhancements and bug fixes to the `Chatroom.svelte` component. The changes improve the user experience by adding new features and fixing existing issues.
* Added a new `isIndividual` property to the `Chatroom` component to handle individual chat sessions.
* Introduced an animated dots feature to indicate ongoing processing or thinking, which updates every 500 milliseconds.
* Implemented a new UI element to display a loading message with animated dots when the last message in an individual conversation is from the user.
* Changed the `scrollToBottom` function to use `requestAnimationFrame` for smoother scrolling and added a delay using `setTimeout` to ensure it scrolls correctly.
* Adjusted the minimum height of the `Textarea` component to improve the …
> feat: show loading message and scroll to buttom in chatroom

- src/lib/components/QrScanner.svelte
This pull request includes a small change to the `QrScanner.svelte` file. The change comments out the line that displays an error notification during scanning.
* [`src/lib/components/QrScanner.svelte`](diffhunk://#diff-fd74a6040d19e4f4a209076e95cfdf92374226f28377f2539e3989215d22127cL42-R42): Commented out the line that displays an error notification during scanning.
> fix: remove qr scan error notification

- package.json
- pnpm-lock.yaml
This pull request includes updates to dependencies in the `package.json` and `pnpm-lock.yaml` files. The most important changes involve the addition and removal of the `@google/generative-ai` dependency.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27): Added `@google/generative-ai` version `^0.21.0` to the dependencies.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L86-R87): Removed `@google/generative-ai` from the dependencies section and adjusted the package manager configuration.
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL9-L12): Removed `@google/generative-ai` from the dependencies section.
* …
> feat: add @google/generative-ai dependency to package.json

- .github/workflows/build-and-push.yml
This pull request includes a small but important change to the GitHub Actions workflow configuration file. The change specifies permissions for the `build-and-push` job.
Permissions update:
* [`.github/workflows/build-and-push.yml`](diffhunk://#diff-ff6530072f2ee96cab1b3a1bd86c4db4afa00ae564f6484789969129711495aeR11-R13): Added `contents: read` and `packages: write` permissions to the `build-and-push` job.
> fix: update permissions for build-and-push workflow

- src/lib/components/Navbar.svelte
- src/lib/stores/language.ts
This pull request includes several changes to the `src/lib/components/Navbar.svelte` file and a small modification to the `src/lib/stores/language.ts` file. The main focus of these changes is to enhance the language selection functionality and update the default language setting.
Enhancements to language selection:
* Added the `Globe` icon from `lucide-svelte` to the imports in `Navbar.svelte`.
* Replaced the flag image logic with text representation for the current language in the `Navbar.svelte` file.
* Updated the language switching logic to correctly handle URL path changes for both English and Chinese languages.
* Introduced a new language dropdown menu with text and icon in the `Navbar.svelte` file, replacing the old toggle button. …
> feat: language setting layout

- src/routes/api/session/[id]/group/[group_number]/conversations/[conv_id]/summary/+server.ts
Key change:
* Implemented a filter to exclude off-topic messages from the chat history before generating the summary. If all messages are off-topic, an early response is returned indicating success. ([src/routes/api/session/[id]/group/[group_number]/conversations/[conv_id]/summary/+server.tsL32-R38](diffhunk://#diff-d884b83ebce09102801e2ecb682d2c5b44f002e3ada7fe632d7a5848e4d5124fL32-R38))
> fix: summary by filter off-topic message from history message list

- .gitignore
- src/lib/server/gemini.ts
- src/lib/server/prompt.ts
- Modified the `cleanForeignLanguage` function to use `revisedText` instead of `revised_text` for consistency with the schema.
- Updated references throughout the codebase to reflect the new variable naming.
- Added `.cursor` to `.gitignore` to exclude cursor files from version control.
- Enhanced the `FOREIGN_LANGUAGE_DETECTION_PROMPT` to align with the updated variable naming.
> Update foreign language detection schema and clean up variable naming

- Dockerfile
This pull request introduces a small but important change to the `Dockerfile`. It adds an environment variable to specify the location of the Google Cloud service account credentials.
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R9-R11): Added the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, pointing to `service-account-file.example.json`, to support Google Cloud authentication.
> fix: add GOOGLE_APPLICATION_CREDENTIALS environment variable in Dockerfile

- src/lib/server/object-storage.ts
- src/routes/api/stt/+server.ts
This pull request refactors the object storage implementation to introduce a pluggable storage adapter architecture, supporting both Cloudflare R2 and Firebase backends. It removes hardcoded logic for backend selection and simplifies the API for uploading objects. Additionally, it updates the STT API to utilize the new storage architecture.
* Introduced a `StorageAdapter` interface and implemented two concrete classes: `CloudflareAdapter` and `FirebaseAdapter`. These classes encapsulate the logic for their respective storage backends (`src/lib/server/object-storage.ts`).
* Replaced environment variable checks and hardcoded backend logic with a `storageService` instance that dynamically selects the appropriate adapter based on the `HINAGIKU_STORAGE_BACKEND` environment variable …
> refactor: object storage

- messages/en.json
- messages/zh.json
- src/lib/components/Chatroom.svelte
- src/lib/components/session/ParticipantView.svelte
internal tracker id: N-001
This pull request introduces a new feature to support Voice Activity Detection (VAD) in the chatroom and participant view components, along with associated UI updates and localization changes. The most important changes include adding a `vadEnabled` property to components, updating the UI to display VAD status, and adding translations for VAD-related terms.
* [`src/lib/components/Chatroom.svelte`](diffhunk://#diff-31a2070f41fdaa274729f68d27df9e502cdb6c29abe9e0525b095d68de81cacdL23-R32): Added a new `vadEnabled` property to the component's props and updated the UI to display the VAD status (enabled/disabled) dynamically. [[1]](diffhunk://#diff-31a2070f41fdaa274729f68d27df9e502cdb6c29abe9e0525b095d68de81cacdL23-R32) …
> feat: add VAD status indicator

- package.json
- pnpm-lock.yaml
- scripts/chatLLM.ts
- src/lib/ai/google.ts
- src/lib/ai/index.ts
- src/lib/ai/openai.ts
- src/lib/server/gemini.ts
- src/lib/server/pdf.ts
- src/lib/stt/gemini.ts
This pull request replaces the Google Gemini Flash model with OpenAI's GPT-4.1 Mini model across multiple files in the codebase. The changes involve updating imports, modifying the LLM model initialization, and ensuring all references to the previous model are updated to use the new one.
* **Model Initialization Updates**:
- Replaced the `GoogleGeminiFlash` model with `llmModel` using OpenAI's GPT-4.1 Mini in `scripts/chatLLM.ts` and `src/lib/ai/google.ts`. Updated the plugin configuration to use OpenAI's API key. [[1]](diffhunk://#diff-4095838e699db8b9d3c80fd2d77efcabe8cb8477f068f48809c7b4535f67adf5L4-R20) [[2]](diffhunk://#diff-69ec65897a11dc7e8bb02d0cac5d8b2dab73155031f859579e67744cdbf920b6L2-R7)
* **Function Updates**:
- Updated all references to `GoogleGeminiFlash.generate` to …
> feat: refactor LLM integration to use unified llmModel across components

- messages/en.json
- messages/zh.json
- src/lib/components/TemplateCard.svelte
- src/lib/components/template/LabelManager.svelte
- src/lib/schema/template.ts
- src/routes/api/template/+server.ts
- src/routes/api/template/[id]/label/+server.ts
- src/routes/dashboard/+page.svelte
- src/routes/template/[id]/+page.svelte
- src/routes/template/[id]/view/+page.svelte
- src/routes/templates/+page.svelte
- src/routes/templates/public/+page.svelte
- allow templates to store `labels`
- expose API to edit template labels
- display labels in template cards
- manage labels from the template editor
- filter public templates by label
- `pnpm lint`
- `pnpm test` *(fails: Service account must be an object)*
> Add labels to templates

- messages/en.json
- messages/zh.json
- src/lib/components/TemplateCard.svelte
- src/lib/components/session/GroupStatus.svelte
This PR addresses several internationalization (i18n) issues, ensuring that the UI displays text in the correct language and that our translation files are synchronized.
*   **Fixed Idle Status Translation**:
*   In the host view, the "idle X seconds" status message was previously hardcoded in English.
*   This has been updated to use the `statusIdle` message from our translation files, allowing it to be displayed in the selected language correctly.
*   *File changed: `src/lib/components/session/GroupStatus.svelte`*
*   **Translated Template Card Statistics**:
*   On the dashboard, the template cards showed "subtasks" and "resources" in English, regardless of the language settings.
*   These have been updated to use the new `subtasksNumber` and `resourcesNumber` keys, which support …
> feat(i18n): Fix translations and sync message files

- messages/en.json
- messages/zh.json
- src/lib/components/session/GroupStatus.svelte
- src/lib/components/session/LabelManager.svelte
This pull request introduces updates to the localization files and refactors several components to improve maintainability and usability. Key changes include adding new localized strings, replacing hardcoded text with dynamic translations, and enhancing the status handling logic in the `GroupStatus` and `LabelManager` components.
* [`messages/en.json`](diffhunk://#diff-5d9e5048516ec2fe83ca06813e79c3b8b44c6c96294f25c7311db311e28eeaeeL450-R452): Added new strings for label length limits and label creation, improving user feedback consistency.
* [`messages/zh.json`](diffhunk://#diff-b1da422c0458d9d7093c9418675ac11a7d276d2d366636a493cca8e90dd75912R325): Added translations for label-related messages and class management actions, ensuring multilingual support for new features. …
> Translations

- src/routes/dashboard/+page.svelte
- src/routes/dashboard/recent/participant/+page.svelte
This pull request refactors label filtering functionality in the dashboard pages. The changes remove the label filtering logic from the host sessions dashboard and reintroduce it in the participant sessions dashboard, improving code organization and aligning functionality with the intended use case.
* **Host Sessions Dashboard (`src/routes/dashboard/+page.svelte`)**:
- Removed label filtering logic, including the `handleLabelSelect` function, `availableLabels` derived store, and associated UI elements for label selection. [[1]](diffhunk://#diff-7f19569e19f8491f516ab38ba78de121c0018cd2f601fcf4141219e1078a7581L85-L102) [[2]](diffhunk://#diff-7f19569e19f8491f516ab38ba78de121c0018cd2f601fcf4141219e1078a7581L295-L305)
* **Participant Sessions Dashboard …
> feat: implement label filtering for participant sessions
